### ISSUE TITLE
Music download link in board yaml file must be in multi-item format

### ISSUE THREAD

**Issue by nikkiwritescode** [FortuneStreetModding/csmm-qt#83]
Here's what I mean. If a board has its music download link set up as follows:
```yaml
music:
  download: https://nikkums.io/cswt/BGM/KoopaTycoonTown.music.zip
```
...we will see an error like this: 
<img width="484" alt="Screenshot 2023-06-18 194545" src="https://github.com/FortuneStreetModding/csmm-qt/assets/26412802/546a3e4f-248c-49a5-b9e8-b1350e2cfc3d">

...but if the yaml is formatted this way:
```yaml
music:
  download: 
    - https://nikkums.io/cswt/BGM/KoopaTycoonTown.music.zip
```

...it works. The former is completely valid yaml, so it's weird to require the latter in the case when only one download link exists.
